const LS_PATIENTS = "synthra_patients";
const LS_APPOINTMENTS = "synthra_appointments";
const LS_HOSPITALS = "synthra_hospitals";

const deskAlert = document.getElementById("desk-alert");
const deskDetails = document.getElementById("desk-details");

function getJSON(key, fallback) {
  const raw = localStorage.getItem(key);
  if (!raw) return fallback;
  try {
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function setJSON(key, value) {
  localStorage.setItem(key, JSON.stringify(value));
}

function setDeskAlert(message) {
  if (!deskAlert) return;
  if (!message) {
    deskAlert.classList.add("hidden");
    deskAlert.textContent = "";
    return;
  }
  deskAlert.textContent = message;
  deskAlert.classList.remove("hidden");
}

function renderDetailsEmpty() {
  deskDetails.innerHTML =
    '<div class="item-meta">Scan a Synthra appointment QR to see details here.</div>';
}

function updateAppointmentStatus(apptId, newStatus) {
  const all = getJSON(LS_APPOINTMENTS, []);
  const idx = all.findIndex((a) => a.id === apptId);
  if (idx === -1) {
    setDeskAlert("Appointment not found in local storage.");
    return;
  }

  all[idx].status = newStatus;
  setJSON(LS_APPOINTMENTS, all);

  setDeskAlert(`Status updated to "${newStatus}".`);
  renderAppointment(apptId);
}


function renderAppointment(apptId) {
  const appointments = getJSON(LS_APPOINTMENTS, []);
  const hospitals = getJSON(LS_HOSPITALS, []);
  const patients = getJSON(LS_PATIENTS, []);

  const ap = appointments.find((a) => a.id === apptId);
  if (!ap) {
    deskDetails.innerHTML =
      '<div class="item-meta" style="color:#fecaca;">Appointment not found.</div>';
    return;
  }

  const hosp = hospitals.find((h) => h.id === ap.hospitalId);
  const patient = patients.find((p) => p.id === ap.patientId);

  const d = new Date(ap.appointmentDate);
  const dateStr = d.toLocaleDateString();
  const timeStr = d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  deskDetails.innerHTML = `
    <div class="desk-row">
      <span class="desk-label">Appointment ID</span>
      <span class="desk-value">${ap.id}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Patient</span>
      <span class="desk-value">${patient ? patient.name : "Unknown"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Phone</span>
      <span class="desk-value">${patient ? patient.phone : "-"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Hospital</span>
      <span class="desk-value">${hosp ? hosp.name : "Unknown hospital"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Date & time</span>
      <span class="desk-value">${dateStr} · ${timeStr}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Status</span>
      <span class="desk-value">${ap.status}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Reason</span>
      <span class="desk-value">${ap.reason || "-"}</span>
    </div>

    <div class="desk-actions">
      <button class="btn-outline btn-small" data-status="confirmed">Mark confirmed</button>
      <button class="btn-outline btn-small" data-status="completed">Mark completed</button>
      <button class="btn-outline btn-small" data-status="cancelled">Cancel visit</button>
    </div>
  `;

  const buttons = deskDetails.querySelectorAll(".desk-actions button");
  buttons.forEach((btn) => {
    btn.addEventListener("click", () => {
      const status = btn.getAttribute("data-status");
      updateAppointmentStatus(ap.id, status);
    });
  });
}


function showInvalidQr(message) {
  setDeskAlert(message || "This is not a valid Synthra appointment QR.");

  deskDetails.innerHTML = `
    <div class="item-meta" style="color:#fecaca;">
      ${message || "Invalid QR: Not a Synthra appointment."}
    </div>
  `;
}

function handleQrText(text) {
  
  const raw = (text || "").trim();
  if (!raw) {
    showInvalidQr("Empty QR content.");
    return;
  }

  let data;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    
    console.error("QR parse error:", e);
    showInvalidQr("Invalid QR: This code was not generated by Synthra.");
    return;
  }

  
  if (!data || data.t !== "synthra_appt" || !data.id) {
    showInvalidQr("Invalid QR: Not a Synthra appointment payload.");
    return;
  }

  
  setDeskAlert(""); 
  renderAppointment(data.id);
}


function initScanner() {
  renderDetailsEmpty();

  if (!window.Html5QrcodeScanner) {
    setDeskAlert("QR scanner library failed to load.");
    return;
  }

  const scanner = new Html5QrcodeScanner("scanner", {
    fps: 10,
    qrbox: 250
  });

  scanner.render(
    (decodedText) => {
      handleQrText(decodedText);
    },
    () => {
          }
  );
}

initScanner();
