// =============== LOCAL STORAGE KEYS ===============
const LS_PATIENTS = "synthra_patients";
const LS_APPOINTMENTS = "synthra_appointments";
const LS_HOSPITALS = "synthra_hospitals";

const deskAlert = document.getElementById("desk-alert");
const deskDetails = document.getElementById("desk-details");

// =============== HELPERS ===============
function getJSON(key, fallback) {
  const raw = localStorage.getItem(key);
  if (!raw) return fallback;
  try {
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function setJSON(key, value) {
  localStorage.setItem(key, JSON.stringify(value));
}

function setDeskAlert(message) {
  if (!deskAlert) return;
  if (!message) {
    deskAlert.classList.add("hidden");
    deskAlert.textContent = "";
    return;
  }
  deskAlert.textContent = message;
  deskAlert.classList.remove("hidden");
}

function renderDetailsEmpty() {
  if (!deskDetails) return;
  deskDetails.innerHTML =
    '<div class="item-meta">Scan a Synthra appointment QR to see details here.</div>';
}

// =============== APPOINTMENT RENDER / UPDATE ===============
function updateAppointmentStatus(apptId, newStatus) {
  const all = getJSON(LS_APPOINTMENTS, []);
  const idx = all.findIndex((a) => a.id === apptId);
  if (idx === -1) {
    setDeskAlert("Appointment not found in local storage.");
    return;
  }

  all[idx].status = newStatus;
  setJSON(LS_APPOINTMENTS, all);

  setDeskAlert(`Status updated to "${newStatus}".`);
  renderAppointment(apptId);
}

function renderAppointment(apptId) {
  const appointments = getJSON(LS_APPOINTMENTS, []);
  const hospitals = getJSON(LS_HOSPITALS, []);
  const patients = getJSON(LS_PATIENTS, []);

  const ap = appointments.find((a) => a.id === apptId);
  if (!ap) {
    deskDetails.innerHTML =
      '<div class="item-meta" style="color:#fecaca;">Appointment not found.</div>';
    return;
  }

  const hosp = hospitals.find((h) => h.id === ap.hospitalId);
  const patient = patients.find((p) => p.id === ap.patientId);

  const d = new Date(ap.appointmentDate);
  const dateStr = d.toLocaleDateString();
  const timeStr = d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });

  deskDetails.innerHTML = `
    <div class="desk-row">
      <span class="desk-label">Appointment ID</span>
      <span class="desk-value">${ap.id}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Patient</span>
      <span class="desk-value">${patient ? patient.name : "Unknown"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Phone</span>
      <span class="desk-value">${patient ? patient.phone : "-"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Hospital</span>
      <span class="desk-value">${hosp ? hosp.name : "Unknown hospital"}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Date & time</span>
      <span class="desk-value">${dateStr} · ${timeStr}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Status</span>
      <span class="desk-value">${ap.status}</span>
    </div>
    <div class="desk-row">
      <span class="desk-label">Reason</span>
      <span class="desk-value">${ap.reason || "-"}</span>
    </div>

    <div class="desk-actions">
      <button class="btn-outline btn-small" data-status="confirmed">Mark confirmed</button>
      <button class="btn-outline btn-small" data-status="completed">Mark completed</button>
      <button class="btn-outline btn-small" data-status="cancelled">Cancel visit</button>
    </div>
  `;

  const buttons = deskDetails.querySelectorAll(".desk-actions button");
  buttons.forEach((btn) => {
    btn.addEventListener("click", () => {
      const status = btn.getAttribute("data-status");
      updateAppointmentStatus(ap.id, status);
    });
  });
}

// =============== QR VALIDATION ===============
function showInvalidQr(message) {
  setDeskAlert(message || "This is not a valid Synthra appointment QR.");

  deskDetails.innerHTML = `
    <div class="item-meta" style="color:#fecaca;">
      ${message || "Invalid QR: Not a Synthra appointment."}
    </div>
  `;
}

function handleQrText(text) {
  const raw = (text || "").trim();
  if (!raw) {
    showInvalidQr("Empty QR content.");
    return;
  }

  let data;
  try {
    data = JSON.parse(raw);
  } catch (e) {
    console.error("QR parse error:", e);
    showInvalidQr("Invalid QR: This code was not generated by Synthra.");
    return;
  }

  if (!data || data.t !== "synthra_appt" || !data.id) {
    showInvalidQr("Invalid QR: Not a Synthra appointment payload.");
    return;
  }

  setDeskAlert(""); // clear
  renderAppointment(data.id);
}

// =============== CAMERA + DRAG & DROP ===============
let html5QrCode = null;
let currentCameraId = null;

async function initScanner() {
  renderDetailsEmpty();

  if (!window.Html5Qrcode) {
    setDeskAlert("QR scanner library failed to load.");
    return;
  }

  html5QrCode = new Html5Qrcode("scanner");

  try {
    const devices = await Html5Qrcode.getCameras();
    if (!devices || devices.length === 0) {
      setDeskAlert("No camera found on this device. You can still upload a QR image below.");
      return;
    }

    currentCameraId = devices[0].id;

    await html5QrCode.start(
      currentCameraId,
      {
        fps: 10,
        qrbox: { width: 250, height: 250 },
      },
      (decodedText) => {
        handleQrText(decodedText);
      },
      () => {
        // ignore per-frame errors
      }
    );

    setDeskAlert("Camera ready. Point a Synthra QR or drag & drop a QR image below.");
  } catch (err) {
    console.error("Camera init error:", err);
    setDeskAlert("Unable to access camera. You can still drag & drop a QR image below.");
  }
}

function setupDragAndDrop() {
  const dropZone = document.getElementById("drop-zone");
  const fileInput = document.getElementById("file-input");

  if (!dropZone || !fileInput) return;

  // Prevent browser from opening the file when dropped anywhere
  ["dragenter", "dragover", "dragleave", "drop"].forEach((eventName) => {
    document.addEventListener(eventName, (e) => {
      e.preventDefault();
      e.stopPropagation();
    });
  });

  ["dragenter", "dragover"].forEach((eventName) => {
    dropZone.addEventListener(eventName, (e) => {
      e.preventDefault();
      e.stopPropagation();
      dropZone.classList.add("drop-zone--over");
    });
  });

  ["dragleave", "drop"].forEach((eventName) => {
    dropZone.addEventListener(eventName, (e) => {
      e.preventDefault();
      e.stopPropagation();
      dropZone.classList.remove("drop-zone--over");
    });
  });

  dropZone.addEventListener("drop", (e) => {
    const file = e.dataTransfer.files && e.dataTransfer.files[0];
    if (!file) return;
    handleImageFile(file);
  });

  dropZone.addEventListener("click", () => {
    fileInput.click();
  });

  fileInput.addEventListener("change", (e) => {
    const file = e.target.files && e.target.files[0];
    if (!file) return;
    handleImageFile(file);
    fileInput.value = "";
  });
}

async function handleImageFile(file) {
  if (!file.type.startsWith("image/")) {
    showInvalidQr("Please drop an image file containing a Synthra QR code.");
    return;
  }

  if (!html5QrCode) {
    // if camera init failed, we still need an instance bound to #scanner
    html5QrCode = new Html5Qrcode("scanner");
  }

  setDeskAlert("Processing QR image…");

  // Stop camera scan if running, because scanFile cannot run in parallel
  try {
    await html5QrCode.stop();
  } catch (e) {
    // ignore "not running" errors
  }

  try {
    const decodedText = await html5QrCode.scanFile(file, true);
    handleQrText(decodedText);
    setDeskAlert("QR scanned from image successfully.");
  } catch (err) {
    console.error("Image QR scan error:", err);
    showInvalidQr("Could not read a QR code from this image. Try another one.");
  } finally {
    // Try to restart camera for live scanning (optional)
    if (currentCameraId) {
      try {
        await html5QrCode.start(
          currentCameraId,
          {
            fps: 10,
            qrbox: { width: 250, height: 250 },
          },
          (decodedText) => {
            handleQrText(decodedText);
          },
          () => {}
        );
        setDeskAlert("Camera ready. Point a Synthra QR or drag & drop a QR image below.");
      } catch (restartErr) {
        console.warn("Could not restart camera after image scan:", restartErr);
      }
    }
  }
}

// =============== INIT ===============
document.addEventListener("DOMContentLoaded", () => {
  setupDragAndDrop();
  initScanner();
});
